GET http://localhost:3000/books/?search_q=potter
//----Auth Token [3.2]-----------
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNjY4OTU0MjA4fQ.RLbtA7rE4KAiVj_c1tb3RyHbwlWxKMEz87NDFoGUhro

###

GET http://localhost:3000/books/1/

###

POST http://localhost:3000/users/
Content-Type: application/json

{    
    "username": "rahul123",
    "password": "rahul@456",
    "gender":"male",
    "location":"hyderabad"
}

###
//----Get Access token-----[3.1]--------
POST http://localhost:3000/login/
Content-Type: application/json

{    
    "username": "rahul123",
    "password": "rahul@456"
}

###
//----Get User Profile API--------------
GET http://localhost:3000/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNjY4OTU0MjA4fQ.RLbtA7rE4KAiVj_c1tb3RyHbwlWxKMEz87NDFoGUhro
